apiVersion: federatorai.containers.ai/v1alpha1
kind: AlamedaService
metadata:
  name: my-alamedaservice
  namespace: federatorai
spec:
  keycode:
    codeNumber: GRV7J-LA4TX-KPPIT-S6GRS-NK4EB-ILFRQ
  selfDriving: false             ## to enable resource self-orchestration of the deployed Alameda components
                                ## it is recommended NOT to use ephemeral data storage for Alameda influxdb component when self-Driving is enabled
  enableExecution: true
  enableGui: true
  version: v4.2.293               ## for Alameda components. (exclude grafana and influxdb)
  prometheusService: https://prometheus-k8s.openshift-monitoring:9091
  storages:                     ## see following details for where it is used in each component
    - usage: log                ## storage setting for log
      type: ephemeral           ## ephemeral means emptyDir{}
    - usage: data
      type: ephemeral
  args:
    # FederatoraiAgentGPU:
    #   Datasource:
    #     InfluxDB:
    #       Address: "influx.a.b.c.d"
    #       Username: "iii"
    #       Password: "iiii"
    #     Prometheus:
    #       Address: "prom.a.b.c.d"
    #       Username: "ppp"
    #       Password: "pppp" 
#    - usage: data               ## storage setting for data
#      type: pvc                 ## pvc means PersistentVolumeClaim
#      size: 10Gi                ## mandatory when type=pvc
#      class: "normal"           ## mandatory when type=pvc
