apiVersion: apps/v1
kind: Deployment
metadata:
  name: cert-managet-cert-manager
  namespace: "{{.NameSpace}}"
  labels:
    app: alameda
    component: cert-managet-cert-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alameda
      component: alameda-cert-managet-webhook
  template:
    metadata:
      labels:
        app: alameda
        component: alameda-cert-managet-webhook 
    spec:
      serviceAccountName: cert-managet-cert-manager
      containers:
        - name: cert-manager
          image: "quay.io/jetstack/cert-manager-controller:v0.9.1"
          imagePullPolicy: IfNotPresent
          args:
          - --v=2
          - --cluster-resource-namespace=$(POD_NAMESPACE)
          - --leader-election-namespace=$(POD_NAMESPACE)
          ports:
          - containerPort: 9402
          env:
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
            
