FROM registry.svc.ci.openshift.org/openshift/release:golang-1.10 AS builder
WORKDIR /go/src/github.com/containers-ai/federatorai-operator
COPY . .
ENV NO_DOCKER=1
ENV BUILD_DEST=/go/bin/federatorai-operator
RUN unset VERSION && make build

FROM registry.access.redhat.com/ubi7-dev-preview/ubi-minimal:7.6
COPY --from=builder /go/bin/federatorai-operator /usr/bin/
COPY --from=builder /go/src/github.com/containers-ai/federatorai-operator/etc/operator.yml /etc/federatorai/operator/operator.yml
# COPY --from=builder /go/src/github.com/containers-ai/federatorai-operator/install /manifests
CMD ["/usr/bin/federatorai-operator"]
# LABEL io.openshift.release.operator true
