apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  annotations:
    secret.name: alameda-notifier-webhook-server-cert
  creationTimestamp: null
  name: alameda-notifier-mutating-webhook-configuration
webhooks:
- clientConfig:
    caBundle: Cg==
    service:
      name: alameda-notifier-webhook-service
      namespace: {{.NameSpace}} 
      path: /mutate-notifying-containers-ai-v1alpha1-alamedanotificationchannel
  failurePolicy: Fail
  name: malamedanotificationchannel.containers.ai
  rules:
  - apiGroups:
    - notifying.containers.ai
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - alamedanotificationchannels
- clientConfig:
    caBundle: Cg==
    service:
      name: alameda-notifier-webhook-service
      namespace: {{.NameSpace}} 
      path: /mutate-notifying-containers-ai-v1alpha1-alamedanotificationtopic
  failurePolicy: Fail
  name: malamedanotificationtopic.containers.ai
  rules:
  - apiGroups:
    - notifying.containers.ai
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - alamedanotificationtopics
