apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:    
  labels:
    controller-tools.k8s.io: "1.0"
  name: alamedascalers.autoscaling.containers.ai
spec:
  group: autoscaling.containers.ai
  names:
    kind: AlamedaScaler
    plural: alamedascalers
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: >-
            'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: >-
            'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            customResourceVersion:
              type: string
            enableexecution:
              type: boolean
            policy:
              enum:
              - stable
              - compact
              type: string
            selector:
              description: 'Important: Run "make" to regenerate code after modifying this file'
              type: object
          required:
          - selector
          type: object
        status:
          properties:
            alamedaController:
              properties:
                deploymentconfigs:
                  type: object
                deployments:
                  type: object
              type: object
          type: object
  version: v1alpha1
  additionalPrinterColumns:
  - description: The enable of execution
    JSONPath: .spec.enableexecution
    name: Execution
    type: boolean
  - description: The match labels of selector
    JSONPath: .spec.selector.matchLabels
    name: Selector
    type: string
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
