apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{.NameSpace}}-cert-managet-cert-manager-controller-certificates 
rules:
- apiGroups: 
  - "certmanager.k8s.io" 
  resources: 
  - "certificates"
  - "certificates/status"
  - "certificaterequests"
  - "certificaterequests/status" 
  verbs: 
  - "update" 
- apiGroups: 
  - "certmanager.k8s.io" 
  resources: 
  - "certificates"
  - "certificaterequests"
  - "clusterissuers"
  - "issuers"
  - "orders" 
  verbs: 
  - "get"
  - "list"
  - "watch" 
# We require these rules to support users with the OwnerReferencesPermissionEnforcement
# admission controller enabled:
# https://kubernetes.io/docs/reference/access-authn-authz/admission-controllers/#ownerreferencespermissionenforcement
- apiGroups: 
  - "certmanager.k8s.io" 
  resources: 
  - "certificates/finalizers" 
  verbs: 
  - "update" 
- apiGroups: 
  - "certmanager.k8s.io" 
  resources: 
  - "orders" 
  verbs: 
  - "create"
  - "delete" 
- apiGroups: 
  - "" 
  resources: 
  - "secrets" 
  verbs: 
  - "get"
  - "list"
  - "watch"
  - "create"
  - "update"
  - "delete" 
- apiGroups: 
  - "" 
  resources: 
  - "events" 
  verbs: 
  - "create"
  - "patch" 