apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: {{.NameSpace}}-alameda-notifier-role
rules:
- apiGroups:
  - notifying.containers.ai
  resources:
  - alamedanotificationchannels
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - notifying.containers.ai
  resources:
  - alamedanotificationchannels/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - notifying.containers.ai
  resources:
  - alamedanotificationtopics
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - notifying.containers.ai
  resources:
  - alamedanotificationtopics/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list
  - watch