apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: federatorai-alameda-vpa-executor
rules:
  - apiGroups:
      - "admissionregistration.k8s.io"
    resources:
      - mutatingwebhookconfigurations
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - delete
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
      - list
      - watch
      - patch
      - delete
  - apiGroups:
      - extensions
      - apps
    resources:
      - replicasets
      - deployments
      - statefulsets
    verbs:
      - get
      - list
      - watch
      - update
  - apiGroups:
      - extensions
      - ""
    resources:
      - replicationcontrollers
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - apps.openshift.io
    resources:
      - deploymentconfigs
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - autoscaling.containers.ai
    resources:
      - alamedascalers
      - alamedarecommendations
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - federatorai.containers.ai
    resources:
      - alamedaservices
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - get
      - list
      - watch