apiVersion: v1
kind: Service
metadata:
  labels:
    component: alameda-vpa-executor
  name: alameda-vpa-executor
  namespace: {{.NameSpace}}
spec:
  ports:
  - port: 443
    targetPort: 8000
  selector:
    component: alameda-vpa-executor