# borrowed from https://cloud.weave.works/k8s/scope.yaml?k8s-version=1.9.3
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: federatorai-alameda-weave-scope
  namespace: federatorai
roleRef:
  kind: ClusterRole
  name: federatorai-alameda-weave-scope
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: alameda-weave-scope
    namespace: federatorai
