// +build !ignore_autogenerated

// Code generated by openapi-gen. DO NOT EDIT.

// This file was autogenerated by openapi-gen. Do not edit it manually!

package v1alpha1

import (
	spec "github.com/go-openapi/spec"
	common "k8s.io/kube-openapi/pkg/common"
)

func GetOpenAPIDefinitions(ref common.ReferenceCallback) map[string]common.OpenAPIDefinition {
	return map[string]common.OpenAPIDefinition{
		"github.com/containers-ai/federatorai-operator/pkg/apis/federatorai/v1alpha1.AlamedaService":       schema_pkg_apis_federatorai_v1alpha1_AlamedaService(ref),
		"github.com/containers-ai/federatorai-operator/pkg/apis/federatorai/v1alpha1.AlamedaServiceSpec":   schema_pkg_apis_federatorai_v1alpha1_AlamedaServiceSpec(ref),
		"github.com/containers-ai/federatorai-operator/pkg/apis/federatorai/v1alpha1.AlamedaServiceStatus": schema_pkg_apis_federatorai_v1alpha1_AlamedaServiceStatus(ref),
	}
}

func schema_pkg_apis_federatorai_v1alpha1_AlamedaService(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "AlamedaService is the Schema for the alamedaservices API",
				Properties: map[string]spec.Schema{
					"kind": {
						SchemaProps: spec.SchemaProps{
							Description: "Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"apiVersion": {
						SchemaProps: spec.SchemaProps{
							Description: "APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"metadata": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"),
						},
					},
					"spec": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/containers-ai/federatorai-operator/pkg/apis/federatorai/v1alpha1.AlamedaServiceSpec"),
						},
					},
					"status": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/containers-ai/federatorai-operator/pkg/apis/federatorai/v1alpha1.AlamedaServiceStatus"),
						},
					},
				},
			},
		},
		Dependencies: []string{
			"github.com/containers-ai/federatorai-operator/pkg/apis/federatorai/v1alpha1.AlamedaServiceSpec", "github.com/containers-ai/federatorai-operator/pkg/apis/federatorai/v1alpha1.AlamedaServiceStatus", "k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"},
	}
}

func schema_pkg_apis_federatorai_v1alpha1_AlamedaServiceSpec(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "AlamedaServiceSpec defines the desired state of AlamedaService",
				Properties:  map[string]spec.Schema{},
			},
		},
		Dependencies: []string{},
	}
}

func schema_pkg_apis_federatorai_v1alpha1_AlamedaServiceStatus(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "AlamedaServiceStatus defines the observed state of AlamedaService",
				Properties:  map[string]spec.Schema{},
			},
		},
		Dependencies: []string{},
	}
}
