apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: alameda-notifier-data.pvc
  namespace: {{.NameSpace}}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi