apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-alameda.influxdb.pvc
  namespace: kroos-tutorial
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: '10Gi'